name: SBMines
version: '${project.version}'
main: pye.twenty.sbmines.SBMines
depend:
  - SBEssentials
  - WorldEdit
softdepend:
  - SBParticles
api-version: '1.20'
commands:
  mine:
    description: Manage mines
    permission: sbmines.command.mines